#!/bin/bash

## expects [ethos executable] [*.smt2 to compile] [*.smt2 to run, which includes the second argument]

SRCDIR=../src/

ETHOS=$1
shift

FILE_GEN=$1
shift

FILE_RUN=$1
shift

echo "Recompile via ethos_compile $ETHOS $FILE_GEN"
ethos_compile $ETHOS $FILE_GEN

echo "Run via $ETHOS --run-compile $FILE_RUN"
$ETHOS --run-compile $FILE_RUN
