#!/usr/bin/env bash

## expects [alfc executable] [*.smt2 problem file] [proof file]

ALFC=$1
shift

PROBLEM=$1
shift

PROOF=$1
shift

BASEDIR=$(pwd)
OUTFILE=/tmp/fullproof.smt2

cat << EOF > $OUTFILE
(include "$BASEDIR/proofs/rules/Cvc5.smt2")
EOF

sed -n 's/declare-sort \+\([A-Za-z]\+\) \+0/declare-type \1 ()/p;s/declare-fun \+\([a-zA-Z]\+\) \+(\([ a-zA-Z]\+\)) \+\([a-zA-Z]\+\)/declare-const \1 (-> \2 \3)/p;/declare-const/p' $PROBLEM >> $OUTFILE
sed '/^unsat/d' $PROOF >> $OUTFILE

cat $OUTFILE
$ALFC -v --no-print-let $OUTFILE
