#!/usr/bin/env bash

## expects [cvc5 executable] [*.smt2 problem file]

CVC5=$1
shift

PROBLEM=$1
shift

BASEDIR=$(dirname -- "$( readlink -f -- "$0"; )";)
ALFC=$BASEDIR/../build/src/alfc

PROOFFILE=/tmp/cvc5proof.smt2
CHECKFILE=/tmp/cleanproof.smt2

$CVC5 --produce-proofs --dump-proofs --proof-format-mode=alethelf --proof-granularity=theory-rewrite $PROBLEM | tee $PROOFFILE

cat << EOF > $CHECKFILE
(include "$BASEDIR/../proofs/rules/Cvc5.smt2")
EOF

sed -n 's/declare-sort \+\([A-Za-z1-9]\+\) \+0/declare-type \1 ()/p;/declare-const/p;s/declare-fun \+\([a-zA-Z1-9]\+\) \+(\([ a-zA-Z1-9]*\)) \+\([a-zA-Z1-9]\+\)/declare-const \1 (-> \2 \3)/p' $PROBLEM >> $CHECKFILE
sed '/^unsat/d' $PROOFFILE >> $CHECKFILE

$ALFC --no-print-let $CHECKFILE
