#!/usr/bin/env python3
"""Bind EOC's generated syntax to the constructors in Isabelle's SML export.

Generated by isabelle-meta; edit plugins/isabelle_meta/generate_syntax.py.
The export can rename constructors and expand enumeration abbreviations, so
this last binding step runs after Isabelle exports the checker.
"""

import argparse
import json
from pathlib import Path
import re


def ml_string(value):
    return '"' + ''.join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                         else f'\\{b:03d}' for b in value.encode()) + '"'


def generate(checker, syntax, exported):
    aliases = dict(re.findall(
        r'abbreviation (\w+) where\s+"\1 \\<equiv> ([^"\n]+)"', checker))
    declared = set(re.findall(r'\b(?:UserOp\w*|CRule\w*)\b', checker))
    native_names = set(re.findall(r'\b(?:UserOp\w*|CRule\w*)\b', exported))

    def native(name):
        if name in native_names:
            return name
        # Isabelle's ML serializer collapses repeated underscores. Refuse an
        # ambiguous mapping instead of guessing a collision suffix.
        normalized = re.sub('_+', '_', name)
        candidates = [n for n in declared - aliases.keys()
                      if re.sub('_+', '_', n) == normalized]
        if candidates == [name] and normalized in native_names:
            return normalized
        raise ValueError(f"cannot bind checker constructor to exported ML: {name}")

    def expand(expression):
        def replace(match):
            name = match[0]
            if name not in declared:
                raise ValueError(f"syntax names a missing checker constructor: {name}")
            return "(" + expand(aliases[name]) + ")" if name in aliases else native(name)
        return re.sub(r'\b(?:UserOp\w*|CRule\w*)\b', replace, expression)

    rows = []
    for entry in syntax['operators']:
        arity = entry['arity']
        if arity in ('none', 'opaque'):
            arity = f"Exact {entry['arguments']}"
        else:
            arity = {'left-assoc': 'Left', 'right-assoc': 'Right',
                     'left-assoc-nil': 'LeftNil', 'right-assoc-nil': 'RightNil',
                     'left-assoc-ns-nil': 'LeftNonSingletonNil',
                     'right-assoc-ns-nil': 'RightNonSingletonNil',
                     'chainable': 'Chain', 'pairwise': 'Pairwise',
                     'arg-list': 'ArgList'}[arity]
            if arity in ('Chain', 'Pairwise', 'ArgList'):
                arity += ' ' + ml_string(entry['connector'])
        pattern = '[' + ', '.join(f'x{i + 1}' for i in range(entry['indices'])) + ']'
        head = expand(entry['head'])
        rows.append(f"  ({ml_string(entry['name'])}, {entry['indices']}, {arity},\n"
                    f"    fn {pattern} => {head} | _ => raise Fail \"operator indices\")")
    rules = [f"  ({ml_string(e['name'])}, {expand(e['constructor'])})"
             for e in syntax['rules']]
    definitions = [f"  ({ml_string(e['name'])}, {len(e['params'])}, "
                   f"fn [{', '.join(e['params'])}] => {expand(e['head'])} "
                   '| _ => raise Fail "definition arguments")'
                   for e in syntax['definitions']]
    return ("(* Generated from EOC syntax.json and $EO_CALC$_Checker.thy. *)\n"
            "structure CpcSyntax = struct\nopen CPC;\n"
            "datatype arity = Exact of Int.int | Left | Right | LeftNil | RightNil\n"
            "  | LeftNonSingletonNil | RightNonSingletonNil\n"
            "  | Chain of string | Pairwise of string | ArgList of string;\n"
            "val operators : (string * Int.int * arity * (term list -> term)) list = [\n"
            + ',\n'.join(rows) + "\n];\n"
            "val rules : (string * cRule) list = [\n" + ',\n'.join(rules) + "\n];\n"
            "val definitions : (string * Int.int * (term list -> term)) list = [\n"
            + ',\n'.join(definitions) + "\n];\nend;\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    here = Path(__file__).resolve().parent
    generated = generate((here.parent / '$EO_CALC$_Checker.thy').read_text(),
                         json.loads((here / 'syntax.json').read_text()),
                         (args.output.parent / 'cpc.ML').read_text())
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)


if __name__ == '__main__':
    main()
