theory $EO_CALC$_Checker
  imports Main "HOL.Rat" "HOL.Bit_Operations"
begin

unbundle bit_operations_syntax

definition eoc_pow2 :: "int => int" where
  "eoc_pow2 n = (if n < 0 then 0 else 2 ^ nat n)"

fun eoc_log_rec :: "nat => nat => nat => nat" where
  "eoc_log_rec base 0 value = 0"
| "eoc_log_rec base (Suc fuel) value =
    (if value < base then 0 else Suc (eoc_log_rec base fuel (value div base)))"

definition eoc_int_log :: "int => int => int" where
  "eoc_int_log base value = (if base <= 1 \<or> value <= 0 then 0
    else int (eoc_log_rec (nat base) (nat value) (nat value)))"

fun eoc_find_prefix :: "nat list => nat list => int => int" where
  "eoc_find_prefix needle [] pos = (if needle = [] then pos else -1)"
| "eoc_find_prefix needle (c # cs) pos =
    (if take (length needle) (c # cs) = needle then pos
     else eoc_find_prefix needle cs (pos + 1))"

definition eoc_str_indexof :: "nat list => nat list => int => int" where
  "eoc_str_indexof s needle pos =
    (if pos < 0 \<or> int (length s) < pos then -1
     else eoc_find_prefix needle (drop (nat pos) s) pos)"

fun eoc_key_less :: "int list => int list => bool" where
  "eoc_key_less [] ys = (ys \<noteq> [])"
| "eoc_key_less (x # xs) [] = False"
| "eoc_key_less (x # xs) (y # ys) =
    (if x = y then eoc_key_less xs ys else x < y)"

text \<open>
  Generated by eoc's isabelle-meta backend. A budget bounds the depth of
  program calls. None denotes exhaustion; Some Term_Stuck denotes EO
  evaluation failure. Only Some True from the checker accepts a refutation.
\<close>

$DATATYPES$

$ORDER_KEYS$

$PROGRAMS$

definition check_refutation :: "nat => CArgList => CCmdList => bool" where
  "check_refutation fuel assumptions commands =
    (p__x24eo_x5fchecker_x5fis_x5frefutation fuel assumptions commands = Some True)"

lemma zero_budget_rejects [simp]:
  "\<not> check_refutation 0 assumptions commands"
  by (simp add: check_refutation_def)

end
