theory $EO_CALC$_Checker
  imports Main "HOL.Rat" "HOL.Bit_Operations"
begin

unbundle bit_operations_syntax

text \<open>
  Generated by eoc's isabelle-meta backend. A budget bounds the depth of
  program calls. None denotes exhaustion; Some Term_Stuck denotes EO
  evaluation failure. Only Some True from the checker accepts a refutation.
\<close>

$DATATYPES$

$PROGRAMS$

definition check_refutation :: "nat => CArgList => CCmdList => bool" where
  "check_refutation fuel assumptions commands =
    (p__x24eo_x5fchecker_x5fis_x5frefutation fuel assumptions commands = Some True)"

lemma zero_budget_rejects [simp]:
  "\<not> check_refutation 0 assumptions commands"
  by (simp add: check_refutation_def)

end
