#!/bin/bash

function check_status()
{
status=$?
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi
}

echo "**** Compile ethos"
make -j4
check_status

echo "**** Debug"
#./src/ethos ./out/vcmt-def-cpc.eo --plugin.smt-meta --no-print-dag $@
#get_backtrace ./src/ethos ./out/vcmt-def-cpc.eo --plugin.smt-meta-sygus --no-print-dag -t smt-meta -t smt-meta-sygus $@

get_backtrace ./src/ethos ./out/desugar-pcv.eo --plugin.smt-meta --no-print-dag -t smt-meta -t smt-meta-sygus $@
