#!/bin/bash

TMP_FILE=temp_trim.eo
TEMPLATE_FILE=../plugins/trim_defs/trim_template.eo
OUT_FILE=../plugins/trim_defs/trim.eo

echo "**** Compile ethos"
make -j4

echo "**** Write EO to $TMP_FILE"
# the name of a EO signature
INPUT=$1
# should be the name of a constant or proof rule in $INPUT
TARGET=$2

cat << EOF > $TMP_FILE
; include this directory
(include "$INPUT")
(echo "trim-defs $TARGET")
EOF

echo "**** Run ethos + trim-defs on $TMP_FILE"
echo "Write trim to ../plugins/trim_defs/trim.eo"
./src/ethos --plugin.trim-defs $TMP_FILE > $OUT_FILE
# remove "correct" and echo
sed -i '1d' "$OUT_FILE"

echo "**** Verify it parses"
./src/ethos $OUT_FILE
