#!/bin/bash

CVC5=~/bin/cvc5-test
OUT_DIR=./out

STD_TRIM_OUT=../plugins/trim_defs/trim_gen.eo
STD_DESUGAR_OUT=../plugins/desugar/eo_desugar_gen.eo
STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo
STD_LEAN_CHECKER_OUT=../plugins/lean_meta/lean_meta_checker_gen.lean
STD_LEAN_SMT_EVAL=../plugins/lean_meta/lean_meta_smt_eval.lean
STD_LEAN_SMT_MODEL_OUT=../plugins/lean_meta/lean_meta_smt_model_gen.lean
STD_LEAN_SPEC_OUT=../plugins/lean_meta/lean_meta_spec_gen.lean
# file used to ensure that trim-defs preserves dependencies for term reductions
STD_SMODEL_DEPS=../plugins/model_smt/term_reduce_deps.eo
# the name of a EO signature
INPUT=$1
# should be the name of a constant or proof rule in $INPUT
shift
TARGET=$@
# trim out
INIT_TRIM=$OUT_DIR/lean-cpc-trim.eo
INIT_DESUGAR=$OUT_DIR/lean-cpc-desugar.eo
VCM_DEF_DESUGAR=$OUT_DIR/lean-cpc-defs.eo
VCMT_DEF_DESUGAR=$OUT_DIR/lean-cpc-final.eo
function check_status()
{
status=$?
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi
}

function trim_defs()
{
TMP_TRIM_OUT=$OUT_DIR/temp_trim.eo
# the name of a EO signature
INPUT_FILE=$1
shift
# output file
echo "(include \"../$INPUT_FILE\")" > $TMP_TRIM_OUT
# ensure the dependencies are kept
cat $STD_SMODEL_DEPS >> $TMP_TRIM_OUT
# add commands for each argument
while [[ $# -gt 0 ]]; do
  TARGET_SYM="$1"
  echo "(echo \"trim-defs $TARGET_SYM\")" >> $TMP_TRIM_OUT
  shift
done
./src/ethos --plugin.trim-defs $TMP_TRIM_OUT
check_status
rm -f $TMP_TRIM_OUT
}

echo "********* Generating Lean for $TARGET in $INPUT *********"

# trim dependencies with respect to the proof rule
echo "**** lean_meta: Run ethos + trim-defs on $INPUT and \"$TARGET\" to $INIT_TRIM"
trim_defs $INPUT $TARGET >/dev/null
check_status
cp $STD_TRIM_OUT $INIT_TRIM

echo "**** lean_meta: Run ethos + desugar on $INIT_TRIM to generate $INIT_DESUGAR"
./src/ethos --plugin.desugar $INIT_TRIM >/dev/null
check_status
# we will process proof rules with lean-meta, which has these dependencies.
DESUGAR_DEPS="\$smtx_hash \$eo_reverse_hash \$eot_Bool \$eot_Type \$eot_fun_type \$eot_apply \$eo_mk_apply \$eo_eq \$eo_ite \$eo_requires \$eo_and \$eo_to_smt \$smtx_model_eval \$eo_checker_is_refutation and \$eot_UConst \$eot_USort"
sed -i "s/eo-desugar-deps/$DESUGAR_DEPS/g" $STD_DESUGAR_OUT
sed -i "s/eo-desugar/lean-meta/g" $STD_DESUGAR_OUT
cp $STD_DESUGAR_OUT $INIT_DESUGAR
# Replace the command "(echo "include eo_builtin_smt")" with the premble as defined in Eunoia.
# This file is not a template, but has a fixed definition.
sed -i "/(include \"eo_builtin_smt.eo\")/{
    r ../plugins/desugar/eo_builtin_smt.eo
    d
}" $INIT_DESUGAR
sed -i "/(include \"smt_embed.eo\")/{
    r ../plugins/desugar/smt_embed.eo
    d
}" $INIT_DESUGAR


echo "**** lean_meta: Run ethos + model-smt on $INIT_DESUGAR to generate $VCM_DEF_DESUGAR"
# now compute the model smt
./src/ethos --plugin.model-smt $INIT_DESUGAR >/dev/null
check_status
# make a copy of the current file, the current step will be included into it
cp $INIT_DESUGAR $VCM_DEF_DESUGAR
# include the model semantics, which was generated above
sed -i "/(echo \"include eo_model_sat.*/{
    r ../plugins/model_smt/model_smt_gen.eo
    d
}" $VCM_DEF_DESUGAR

# trim again, where we require keeping the verification condition
echo "**** lean_meta: Run ethos + trim-deps on $VCM_DEF_DESUGAR to generate $VCMT_DEF_DESUGAR"
TARGET_PROGS=$(sed 's/\([^[:space:]]\+\)/\$eo_prog_\1/g' <<< "$TARGET")
trim_defs $VCM_DEF_DESUGAR $TARGET_PROGS >/dev/null
check_status
cp $STD_TRIM_OUT $VCMT_DEF_DESUGAR

echo "**** lean_meta: Verify ethos parses"
./src/ethos $VCMT_DEF_DESUGAR >/dev/null
check_status

echo "**** lean_meta: Generate Lean from $VCMT_DEF_DESUGAR to $OUT_DIR/lean/*.lean"
./src/ethos --plugin.lean-meta $VCMT_DEF_DESUGAR >/dev/null
check_status
cp $STD_LEAN_CHECKER_OUT $OUT_DIR/lean/Logos.lean
cp $STD_LEAN_SMT_EVAL $OUT_DIR/lean/SmtEval.lean
cp $STD_LEAN_SMT_MODEL_OUT $OUT_DIR/lean/SmtModel.lean
cp $STD_LEAN_SPEC_OUT $OUT_DIR/lean/Spec.lean

#echo "**** lean_meta: Verify cvc5 parses"
#$CVC5 $VC_OUT --parse-only
#check_status


# clear temporary files
#rm -f $INIT_TRIM
#rm -f $INIT_DESUGAR
#rm -f $VC_DEF_DESUGAR
#rm -f $VCM_DEF_DESUGAR
#rm -f $VCMT_DEF_DESUGAR
rm -f $STD_TRIM_OUT
rm -f $STD_DESUGAR_OUT
rm -f $STD_SMODEL_OUT
rm -f $STD_VC_OUT
rm -f $STD_LEAN_CHECKER_OUT
rm -f $STD_LEAN_SMT_MODEL_OUT
rm -f $STD_LEAN_SPEC_OUT
