#!/bin/bash
echo "**** Compile ethos"
cmake --build . --target ethos-eoc -j4

echo "**** Run ethos + desugar"
./src/ethos-eoc --plugin.desugar-vc ~/cvc5-ajr/proofs/eo/cpc/Cpc.eo
echo "**** Verify that it parses"
./src/ethos-eoc ../plugins/desugar/eo_desugar_vcs.eo

echo "**** Generate SMT2"
./src/ethos-eoc --plugin.smt-meta ../plugins/smt_meta/eo_model.eo
echo "**** Verify that it parses"
ajr-cvc5 ../plugins/smt_meta/smt_meta_gen.smt2
