#!/bin/bash

#echo "**** Compile ethos"
#make -j4

STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo

TMP_OUT=$1-model.eo

cp $1 $TMP_OUT

# replace the command "(echo "include eo_smt_preamble")" with the premble as defined in Eunoia.
sed -i "/(echo \"include eo_smt_preamble\")/{
    r ../plugins/model_smt/model_smt_preamble.eo
    d
}" $TMP_OUT

# similarly, replace "(echo "include eo_builtin_smt")"
sed -i "/(echo \"include eo_builtin_smt\")/{
    r ../plugins/model_smt/eo_builtin_smt.eo
    d
}" $TMP_OUT

echo "**** run_gen_model: Run ethos + desugar on $1 to generate $STD_SMODEL_OUT"
./src/ethos --plugin.model-smt $1
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi

mv $STD_SMODEL_OUT $STD_SMODEL_OUT.tmp
# the user definitions come first
cp $TMP_OUT $STD_SMODEL_OUT
# then append the filled in template
cat $STD_SMODEL_OUT.tmp >> $STD_SMODEL_OUT
rm -f $TMP_OUT

#echo "**** run_gen_model: Verify it parses"
#./src/ethos $STD_SMODEL_OUT
