#!/bin/bash

CVC5=~/bin/cvc5-test
OUT_DIR=./out

STD_DESUGAR_OUT=../plugins/desugar/eo_desugar_gen.eo
STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo
STD_LEAN_CHECKER_OUT=../plugins/lean_meta/lean_meta_checker_gen.lean
STD_LEAN_SMT_EVAL=../plugins/lean_meta/lean_meta_smt_eval.lean
STD_LEAN_SMT_MODEL_OUT=../plugins/lean_meta/lean_meta_smt_model_gen.lean
STD_LEAN_SPEC_OUT=../plugins/lean_meta/lean_meta_spec_gen.lean
STD_LEAN_LEMMAS_OUT=../plugins/lean_meta/lean_meta_lemmas_gen.lean
# the name of a EO signature
# INPUT = $1
INPUT="../../cvc5-ajr/proofs/eo/cpc/Cpc.eo"
#INPUT="../../AletheInEunoia/signature/Alethe.eo"
INIT_DESUGAR=$OUT_DIR/lean-cpc-desugar.eo
VCM_DEF_DESUGAR=$OUT_DIR/lean-cpc-final.eo
function check_status()
{
status=$?
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi
}

echo "**** Compile ethos"
make -j4
check_status

echo "********* Generating Lean for $INPUT *********"

echo "**** lean_meta: Run ethos + desugar on $INPUT to generate $INIT_DESUGAR"
./src/ethos --plugin.desugar $INPUT >/dev/null
check_status
# we will process proof rules with lean-meta, which has these dependencies.
DESUGAR_DEPS="\$smtx_hash \$eo_reverse_hash \$eot_Bool \$eot_Type \$eot_fun_type \$eot_apply \$eo_mk_apply \$eo_eq \$eo_ite \$eo_requires \$eo_and \$eo_to_smt \$smtx_model_eval \$eo_checker_is_refutation and \$eot_UConst \$eot_USort"
sed -i "s/eo-desugar-deps/$DESUGAR_DEPS/g" $STD_DESUGAR_OUT
sed -i "s/eo-desugar/lean-meta/g" $STD_DESUGAR_OUT
cp $STD_DESUGAR_OUT $INIT_DESUGAR
# Replace the command "(echo "include eo_builtin_smt")" with the premble as defined in Eunoia.
# This file is not a template, but has a fixed definition.
sed -i "/(include \"eo_builtin_smt.eo\")/{
    r ../plugins/desugar/eo_builtin_smt.eo
    d
}" $INIT_DESUGAR
sed -i "/(include \"smt_embed.eo\")/{
    r ../plugins/desugar/smt_embed.eo
    d
}" $INIT_DESUGAR

echo "**** lean_meta: Run ethos + model-smt on $INIT_DESUGAR to generate $VCM_DEF_DESUGAR"
./src/ethos --plugin.model-smt $INIT_DESUGAR >/dev/null
check_status
cp $INIT_DESUGAR $VCM_DEF_DESUGAR
# include the model semantics, which was generated above
sed -i "/(echo \"include eo_model_sat.*/{
    r ../plugins/model_smt/model_smt_gen.eo
    d
}" $VCM_DEF_DESUGAR

echo "**** lean_meta: Verify ethos parses"
./src/ethos $VCM_DEF_DESUGAR >/dev/null
check_status

echo "**** lean_meta: Generate Lean from $VCM_DEF_DESUGAR to $OUT_DIR/lean/*.lean"
./src/ethos --plugin.lean-meta $VCM_DEF_DESUGAR >/dev/null
check_status
cp $STD_LEAN_CHECKER_OUT $OUT_DIR/lean/Logos.lean
cp $STD_LEAN_SMT_EVAL $OUT_DIR/lean/SmtEval.lean
cp $STD_LEAN_SMT_MODEL_OUT $OUT_DIR/lean/SmtModel.lean
cp $STD_LEAN_SPEC_OUT $OUT_DIR/lean/Spec.lean
cp $STD_LEAN_LEMMAS_OUT $OUT_DIR/lean/Lemmas.lean

#echo "**** lean_meta: Verify cvc5 parses"
#$CVC5 $VC_OUT --parse-only
#check_status


# clear temporary files
#rm -f $INIT_TRIM
#rm -f $INIT_DESUGAR
#rm -f $VC_DEF_DESUGAR
#rm -f $VCM_DEF_DESUGAR
#rm -f $VCMT_DEF_DESUGAR
rm -f $STD_DESUGAR_OUT
