#!/bin/bash

TMP_FILE=temp_trim.eo

#echo "**** Compile ethos"
#make -j4

echo "**** run_trim_defs: Write EO to $TMP_FILE"
# the name of a EO signature
INPUT=$1
shift
# output file
STD_TRIM_OUT=../plugins/trim_defs/trim.eo

echo "(include \"$INPUT\")" > $TMP_FILE

# add commands for each argument
while [[ $# -gt 0 ]]; do
  TARGET="$1"
  echo "(echo \"trim-defs $TARGET\")" >> $TMP_FILE
  shift
done

echo "**** run_trim_defs: Run ethos + trim-defs on $TMP_FILE"
echo "Write trim to ../plugins/trim_defs/trim.eo"
./src/ethos --plugin.trim-defs $TMP_FILE > $STD_TRIM_OUT
# TODO: make consistent with other plugins?
# remove "correct"
sed -i '1d' "$STD_TRIM_OUT"

#echo "**** Verify it parses"
#./src/ethos $OUT_FILE

#rm -f $TMP_FILE
