#!/bin/bash

OUT_DIR=./out

STD_TRIM_OUT=../plugins/trim_defs/trim_gen.eo
STD_DESUGAR_OUT=../plugins/desugar/eo_desugar_gen.eo
STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo
STD_SMODEL_EMBED_OUT=../plugins/model_smt/model_eo_embed_gen.eo
STD_VC_OUT=../plugins/smt_meta/smt_meta_gen.smt2
# the name of a EO signature
INPUT=$1
# should be the name of a constant or proof rule in $INPUT
TARGET=$2
# trim out
INIT_TRIM=$OUT_DIR/trim-cpc.eo
INIT_DESUGAR=$OUT_DIR/trim-d-cpc.eo
VC_DEF_DESUGAR=$OUT_DIR/vc-def-cpc.eo
VCM_DEF_DESUGAR=$OUT_DIR/vcm-def-cpc.eo
VCMT_DEF_DESUGAR=$OUT_DIR/vcmt-def-cpc.eo
VC_OUT=$OUT_DIR/vc/final-cpc-$TARGET.smt2
function check_status()
{
status=$?
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi
}

function trim_defs()
{
TMP_TRIM_OUT=temp_trim.eo
# the name of a EO signature
INPUT_FILE=$1
shift
# output file
echo "(include \"$INPUT_FILE\")" > $TMP_TRIM_OUT
# add commands for each argument
while [[ $# -gt 0 ]]; do
  TARGET_SYM="$1"
  echo "(echo \"trim-defs $TARGET_SYM\")" >> $TMP_TRIM_OUT
  shift
done
./src/ethos --plugin.trim-defs $TMP_TRIM_OUT
check_status
rm -f $TMP_TRIM_OUT
}

echo "********* Verifying the correctness of $TARGET *********"

echo "**** smt_meta: Run ethos + trim-defs on $INPUT and $TARGET to $INIT_TRIM"
#./run_trim_defs $INPUT $TARGET "\$eo_model_sat" >/dev/null
trim_defs $INPUT $TARGET >/dev/null
check_status
cp $STD_TRIM_OUT $INIT_TRIM

echo "**** smt_meta: Run ethos + desugar on $INIT_TRIM to generate $INIT_DESUGAR"
./src/ethos --plugin.desugar-vc $INIT_TRIM >/dev/null
check_status
cp $STD_DESUGAR_OUT $INIT_DESUGAR

# TODO: revisit dependencies in trim defs steps
# note that all symbols that are used downstream must be manually kept
# in particular this means that we keep the following:
# - the verification condition
# - the builtin literals
# - the type rules
echo "**** smt_meta: Run ethos + trim-deps on $INIT_DESUGAR to generate $VC_DEF_DESUGAR"
#  "\$eo_is_bool" "\$eo_is_z" "\$eo_is_q" "\$eo_is_str" "\$eo_is_bin"
trim_defs $INIT_DESUGAR "\$eovc_$TARGET" >/dev/null
check_status
cp $STD_TRIM_OUT $VC_DEF_DESUGAR
# "\$eo_List" "\$eo_List_nil" "\$eo_List_cons" "\$eo_fail"

# eliminate these operators here, as desugar doesn't do this currently
sed -i -e 's/eo::list/\$eo_list/g' -e 's/eo::eq /\$eo_eq /g' $VC_DEF_DESUGAR


echo "**** smt_meta: Run ethos + model-smt on $VC_DEF_DESUGAR to generate $VCM_DEF_DESUGAR"
# make a copy of the current file, the current step will be included into it
TMP_OUT=$(mktemp)
cp $VC_DEF_DESUGAR $TMP_OUT
# Replace the command "(echo "include eo_builtin_smt")" with the premble as defined in Eunoia.
# This file is not a template, but has a fixed definition.
sed -i "/(echo \"include eo_builtin_smt.*/{
    r ../plugins/model_smt/eo_builtin_smt.eo
    d
}" $TMP_OUT
# now compute the model smt
./src/ethos --plugin.model-smt $TMP_OUT >/dev/null
check_status
# include the model semantics, which was generated above
sed -i "/(echo \"include eo_model_sat.*/{
    r ../plugins/model_smt/model_smt_gen.eo
    d
}" $TMP_OUT
mv $TMP_OUT $VCM_DEF_DESUGAR
rm -f $TMP_OUT

# should not eliminate remaining eo:: here
sed -i -e 's/eo::/\$eo_/g' -e 's/\$eo_quote/eo::quote/g' -e 's/\$eo_define/eo::define/g' $VCM_DEF_DESUGAR

# trim again, where we require keeping the verification condition
echo "**** smt_meta: Run ethos + trim-deps on $VCM_DEF_DESUGAR to generate $VCMT_DEF_DESUGAR"
trim_defs $VCM_DEF_DESUGAR "\$eovc_$TARGET" >/dev/null
check_status
cp $STD_TRIM_OUT $VCMT_DEF_DESUGAR

echo "**** smt_meta: Verify ethos parses"
./src/ethos $VCMT_DEF_DESUGAR >/dev/null
check_status

echo "**** smt_meta: Generate SMT2 from $VCMT_DEF_DESUGAR to $VC_OUT"
./src/ethos --plugin.smt-meta $VCMT_DEF_DESUGAR >/dev/null
check_status
cp $STD_VC_OUT $VC_OUT

# TODO: trim-defs again??

echo "**** smt_meta: Verify cvc5 parses"
ajr-cvc5 $VC_OUT --parse-only
check_status

echo "**** smt_meta: Run the final verification condition with unsat cores"
ajr-cvc5 $VC_OUT --dump-unsat-cores --quant-ind #--parse-only
check_status

echo "**** smt_meta: Run the final verification condition with proofs"
ajr-cvc5 $VC_OUT --check-proofs --stats-internal --quant-ind |& grep -P '(^unknown$|^unsat$|^sat$|finalProof::ruleCount|finalProof::totalRuleCount|finalProof::ruleUnhandled|finalProof::trust)'
check_status

# clear temporary files
#rm -f $INIT_TRIM
#rm -f $INIT_DESUGAR
#rm -f $VC_DEF_DESUGAR
#rm -f $VCM_DEF_DESUGAR
#rm -f $VCMT_DEF_DESUGAR
rm -f $STD_TRIM_OUT
rm -f $STD_DESUGAR_OUT
rm -f $STD_SMODEL_OUT
rm -f $STD_SMODEL_EMBED_OUT
rm -f $STD_VC_OUT
