#!/bin/bash

#echo "**** Compile ethos"
#make -j4

STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo

TMP_OUT=$1-model.eo

echo "**** run_gen_model: Run ethos + desugar on $1 to generate $STD_SMODEL_OUT"
./src/ethos --plugin.model-smt $1
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi

cp $STD_SMODEL_OUT $TMP_OUT
# the user definitions come first
cp $1 $STD_SMODEL_OUT
# then append the filled in template
cat $TMP_OUT >> $STD_SMODEL_OUT
rm -f $TMP_OUT

#echo "**** run_gen_model: Verify it parses"
#./src/ethos $STD_SMODEL_OUT
