#!/bin/bash

#echo "**** Compile ethos"
#make -j4

STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo

echo "**** run_gen_model_smt: Run ethos + model-smt on $1 to generate $STD_SMODEL_OUT"
./src/ethos --plugin.model-smt $1
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi

TMP_OUT=tmp.eo

cp $1 $TMP_OUT

# Replace the command "(echo "include eo_builtin_smt")" with the premble as defined in Eunoia.
# This file is not a template, but has a fixed definition.
sed -i "/(echo \"include eo_builtin_smt\")/{
    r ../plugins/model_smt/eo_builtin_smt.eo
    d
}" $TMP_OUT

# include the model semantics, which was generated above
sed -i "/(echo \"include eo_model_sat\")/{
    r ../plugins/model_smt/model_smt_gen.eo
    d
}" $TMP_OUT

# Now put the final Eunoia file at the target location
mv $TMP_OUT $STD_SMODEL_OUT

#echo "**** run_gen_model: Verify it parses"
#./src/ethos $STD_SMODEL_OUT
