#!/bin/bash

OUT_DIR=./out

STD_TRIM_OUT=../plugins/trim_defs/trim_gen.eo
STD_DESUGAR_OUT=../plugins/desugar/eo_desugar_gen.eo
STD_SMODEL_OUT=../plugins/model_smt/model_smt_gen.eo
STD_SMODEL_EMBED_OUT=../plugins/model_smt/model_eo_embed_gen.eo
STD_VC_OUT=../plugins/smt_meta/smt_meta_gen.smt2
# file used to ensure that trim-defs preserves dependencies for term reductions
STD_SMODEL_DEPS=../plugins/model_smt/term_reduce_deps.eo

# should be the name of a proof file
INPUT=$1
# trim out
INIT_DESUGAR=$OUT_DIR/desugar-pcv.eo
INPUT_FILE=$(basename -- "$INPUT")
PC_VALID_OUT=$OUT_DIR/pcv/check-$INPUT_FILE.smt2

function check_status()
{
status=$?
if [[ $status -eq 0 ]]; then
  echo "success"
else
  exit $status
fi
}

echo "********* Validating equivalence of proof checking for $INPUT *********"

echo "**** Compile ethos"
make -j4
check_status

echo "**** smt_meta: Run ethos + desugar on $INPUT to generate $INIT_DESUGAR"
./src/ethos --plugin.desugar $INPUT >/dev/null
check_status
cp $STD_DESUGAR_OUT $INIT_DESUGAR

# Replace the command "(echo "include eo_builtin_smt")" with the premble as defined in Eunoia.
# This file is not a template, but has a fixed definition.
sed -i "/(echo \"include eo_builtin_smt.*/{
    r ../plugins/model_smt/eo_builtin_smt.eo
    d
}" $INIT_DESUGAR

echo "**** smt_meta: Generate SMT2 from $INIT_DESUGAR to $PC_VALID_OUT"
./src/ethos --plugin.smt-meta $INIT_DESUGAR >/dev/null
check_status
cp $STD_VC_OUT $PC_VALID_OUT

echo "**** smt_meta: Verify cvc5 parses"
ajr-cvc5 $PC_VALID_OUT --parse-only
check_status
  
echo "**** smt_meta: Run proof validation"
ajr-cvc5 $PC_VALID_OUT
check_status

# clear temporary files
rm -f $STD_DESUGAR_OUT
rm -f $STD_VC_OUT
